return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 6,
  nextobjectid = 61,
  properties = {
    ["music"] = "Who Might You Be"
  },
  tilesets = {
    {
      name = "castle",
      firstgid = 1,
      filename = "../tilesets/castle.tsx",
      exportfilename = "../tilesets/castle.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        33, 31, 33, 33, 33, 31, 33, 33, 33, 33, 33, 33, 31, 33, 33, 33,
        38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 15, 15, 26, 27,
        32, 33, 33, 31, 33, 33, 33, 33, 31, 33, 33, 34, 15, 15, 32, 31,
        32, 31, 33, 33, 33, 33, 31, 33, 33, 33, 33, 34, 15, 15, 32, 33
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 5,
      name = "Tile Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 20.4545,
      offsety = 42.1818,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 44, 45, 46, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 50, 51, 52, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 56, 57, 58, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 3,
          name = "spawn",
          type = "",
          shape = "point",
          x = 320,
          y = 280,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "entry",
          type = "",
          shape = "point",
          x = 521,
          y = 415.667,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 80,
          width = 40,
          height = 320,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 360,
          width = 478,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 80,
          width = 40,
          height = 280,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 40,
          width = 640,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 360,
          width = 40,
          height = 120,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 360,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 400,
          width = 37.625,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 32,
          name = "chest",
          type = "",
          shape = "point",
          x = 280,
          y = 425,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["money"] = "999"
          }
        },
        {
          id = 34,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = -1.71212,
          y = 296,
          width = 12.5,
          height = 63.3788,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1"] = "* There's a sign![wait:5] Yep.[wait:5] \nIt's a cool sign with cool text that's totally awesome.",
            ["text2"] = "[voice:susie][face:susie/smile]* Hey,[wait:5] that's a pretty \ncool sign!",
            ["text3"] = "[voice:ralsei][face:ralsei/smile]* Yes![wait:5] I love the \nsigney-ness of it!",
            ["text4"] = "[voice:susie][face:susie/surprise_smile]* Hey,[wait:5] look![wait:5] \nThere's another!",
            ["text5"] = "[voice:susie][face:susie/smile]* Heh,[wait:5] let's see what \nthis one sa[next]",
            ["text6"] = "[voice:susie][face:susie/suspicious] * ...",
            ["text7"] = "[voice:susie][face:susie/sus_nervous]* Kris,[wait:5] \n* let's uh...[wait:5] \n* go."
          }
        },
        {
          id = 36,
          name = "savepoint",
          type = "",
          shape = "point",
          x = 520,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "room_center",
          type = "",
          shape = "point",
          x = 320,
          y = 200,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "npc",
          type = "",
          shape = "point",
          x = -40,
          y = 120,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "sans",
            ["turn"] = true
          }
        },
        {
          id = 49,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 476,
          y = 439,
          width = 90,
          height = 22,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "plaza",
            ["marker"] = "entry",
            ["stairs"] = "true"
          }
        },
        {
          id = 53,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = -1.33333,
          y = 77,
          width = 13.5,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1"] = "[voice:sans][face:sans/neutral]* heya kid.",
            ["text2"] = "[voice:sans][face:sans/look_left]* wanna join me in this wall? it's pretty cozy.",
            ["text3"] = "[voice:sans][face:sans/closed]* not a fan? \nok suit yourself."
          }
        },
        {
          id = 54,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 287.818,
          y = 96.3636,
          width = 64.1818,
          height = 43.2727,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "examples.spin"
          }
        },
        {
          id = 56,
          name = "npc",
          type = "",
          shape = "point",
          x = 320,
          y = 120,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["actor"] = "aqua",
            ["text1"] = "[image:aquaf, 0, 0, 2, 2] Uuuuu! Kris! Let's play sometime, okay!!!"
          }
        },
        {
          id = 59,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 200.5,
          y = 352,
          width = 157.5,
          height = 20.5,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1"] = "* Just perfectly out of reach",
            ["text2"] = "[voice:susie][face:susie/teeth_smile]* Hey Kris,[wait:5]think Ralsei  \nknows \"Pickaxe Fome\"?"
          }
        }
      }
    }
  }
}
