return {
    talk = function(cutscene, event)
    
    Game.world.music:pause()
    cutscene:look("may", "left")
    cutscene:look("seth", "right")
    cutscene:wait(cutscene:panTo(320, 200, 1, "linear"))
    --dialogue start
    Game.world.music:play("Wait a Second", 1)
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]So...[wait:5] uh...[wait:5] what do you like to do in your free time...?")
    cutscene:text("[voice:maytxt]* Oh![wait:5] sometimes I like to play Minecrap,[wait:5] hang out with my girlfriend (not canon to JR)...")
    cutscene:text("[voice:maytxt]* Organise my Pokemon Cards...")
    cutscene:text("[voice:maytxt]* [wait:5]And sit in front of my computer and stare at it on hours on end until the heat death of the universe where everyone I know and love will perish in a firey blaze along side me and everything I spent years of my life working on![next]")
    cutscene:text("[voice:maytxt]* What do you like to do?")
    cutscene:setAnimation("seth", "nervous")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]...I uh...[wait:5] like reading.")
    cutscene:resetSprite("seth")
    cutscene:look("seth", "right")
    cutscene:text("[voice:maytxt]* Cool![wait:5] I personally like video essays.")

    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]I love binge watching those!")
    cutscene:text("[voice:maytxt]* Have you seen the one about device theory?")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]Yeah.[wait:5] I personally don't buy it but...[wait:5] what do you two think?")
    
    Game.world.music:pause()
    cutscene:look("seth", "down")
    cutscene:look("may", "down")

    cutscene:wait(3) --I know who you are.

    Game.world.music:resume()
    cutscene:look("may", "left")
    cutscene:look("seth", "right")
    
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]Do you uh... Have any siblings?")
    cutscene:text("[voice:maytxt]* Yeah. A younger one and an even younger one. (Also not canon to JR.)") --wip
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]You're the oldest?")
    cutscene:text("[voice:maytxt]* Yep.[wait:5] Do you have any siblings?")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]Heh,[wait:5] my inferiors?")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]I mean...[wait:5] I guess Aqua is like a little sister to me.")
    cutscene:text("[voice:maytxt]* Is she the one who's running around and making the World Revolve?")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]Sounds like her!")
    cutscene:text("[voice:maytxt]* She seems fun to be around![wait:5] We all need a little Chaos in our lives!")

    cutscene:walkTo("kim", 1, 320, 0.5, "right")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]Well...[wait:5] She's a...[wait:5] handful...")
    cutscene:look("kim", "left")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]She's young though...[wait:5] or at least acts young.")
    cutscene:walkTo("kim", -40, 320, 1, "left")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]Even through her...[wait:5] immaturity though,[wait:5] I do think she can actually be a-")
    --aqua jumps in
    cutscene:walkTo("kim", -80.0, 240.0, 1.5, "right")
    Game.world.music:pause()
    cutscene:wait(cutscene:jumpTo("aqua", 320, 320, 10, 1, "spin"))
    cutscene:look("aqua", "up")

    cutscene:text("[image:aquaf, 0, 0, 2, 2][color:#24deff] Uuuuu![wait:5] Hi Seth!")
    Game.world.music:play("Who Might You Be", 0.6)
    cutscene:setAnimation("seth", "WHAT")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]Aqua?![wait:5] What are you doing here?![wait:5] I'm busy!")
    cutscene:wait(cutscene:jumpTo("aqua", 360, 200, 10, 0.5, "spin"))
    cutscene:setAnimation("aqua", "wave")
    cutscene:look("may", "up")
    cutscene:resetSprite("seth")
    cutscene:look("seth", "right")
    cutscene:text("[image:aquaf, 0, 0, 2, 2][color:#24deff] Uuuu![wait:5] Hi Miss Ghost Lady!")
    cutscene:wait(cutscene:jumpTo("aqua", 320, 320, 10, 0.5, "spin"))
    cutscene:look("may", "down")
    cutscene:look("seth", "down")
    cutscene:setAnimation("aqua", "laugh")
    cutscene:text("[image:aquaf, 0, 0, 2, 2][color:#24deff] Seth![wait:5] You never told me you had a girlfriend!")
    cutscene:walkTo("kim", 40.0, 240.0, 1.5, "right")
    cutscene:setAnimation("seth", "WHAT")
    cutscene:shakeCharacter("seth", 2, 1, 0.5)
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]W-[wait:5]WHAT?!")
    cutscene:shakeCharacter("seth", 2, 1, 0.5)
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]WE'RE NOT-")
    cutscene:shakeCharacter("seth", 2, 1, 0.5)
    cutscene:walkTo("kim", 160.0, 240.0, 1.5, "right")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]I DON'T-")
    cutscene:shakeCharacter("seth", 2, 1, 0.5)
    cutscene:walkTo("kim", 280.0, 240.0, 2, "right")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]WHERE DID YOU GET THAT FROM?!?!?!")
    cutscene:walkTo("kim", 280, 260.75, 1, "down")
    cutscene:shakeCharacter("seth", 2, 1, 0.5)
    cutscene:text("[voice:maytxt]* Heh,[wait:5] I'm only into [glow:210, 115, 1, 0, 0, 1][color:red]WOMEN[color:reset]!")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]SEE?!")
    cutscene:shakeCharacter("kim", 2, 1, 0.5)
    cutscene:text("[image:aquaf, 0, 0, 2, 2][color:#24deff] Uuuu![wait:5] Okay!")
    cutscene:shakeCharacter("kim", 2, 1, 0.5)
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]Also you didn't answer my question![wait:5] What ARE you doing here?")
    cutscene:look("may", "left")
    cutscene:wait(cutscene:alert("may"))
    cutscene:text("[voice:maytxt]* Seth-")
    cutscene:text("* I GOT IT![wait:5] RUN AQUA RUN!")
    cutscene:jumpTo("aqua", 680.0, 240.0, 10, 1, "spin")
    cutscene:walkTo("kim", 680.0, 260.75, 1.5, "right")
    --run off
    cutscene:resetSprite("seth")
    cutscene:setAnimation("seth", "WAIT")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]W-WAIT!!!!")
    cutscene:resetSprite("seth")
    cutscene:wait(cutscene:walkTo("seth", 440.0, 280.0, 0.5))
    cutscene:look("may", "right")
    cutscene:setAnimation("seth", "fall")
    cutscene:wait(cutscene:alert("may"))
    cutscene:text("[voice:maytxt]* A-[wait:5]are you okay?!")
    cutscene:wait(cutscene:walkTo("may", 480.0, 320.0, 0.4))
    cutscene:look("may", "up")
    cutscene:text("[voice:maytxt]* Here let me...")
    cutscene:shakeCharacter("may", 2, 1, 0.5)
    cutscene:playSound("bump")
    cutscene:wait(1)
    cutscene:shakeCharacter("may", 2, 1, 0.5)
    cutscene:playSound("bump")
    cutscene:wait(1)
    cutscene:shakeCharacter("may", 2, 1, 0.5)
    cutscene:playSound("wing")

    cutscene:resetSprite("seth")
    cutscene:look("seth", "down")
    cutscene:wait(2)
    cutscene:setAnimation("seth", "nervous")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]...Th-[wait:5] thanks...")
    cutscene:wait(1.5)
    cutscene:shakeCharacter("seth", 2, 1, 0.5)
    cutscene:setAnimation("seth", "WHAT")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]Wh-[wait:5] wait if they see that page then they'll see-")
    cutscene:text("[image:aquaf, 0, 0, 2, 2][color:#24deff] Uuuuu![wait:5] Kim![wait:5] What does 'Kerdly' mean??")
    cutscene:wait(1.5)
    cutscene:setAnimation("seth", "nervous")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]I-[wait:5]I'm sure it's fine...")
    cutscene:wait(cutscene:jumpTo("aqua", 440.0, 360, 10, 1, "spin"))
    cutscene:text("[image:aquaf, 0, 0, 2, 2][color:#24deff] Uuuuu![wait:5] Seth![wait:5] Look at what we added!")
    cutscene:setAnimation("seth", "read")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]Oh you...[wait:5] are actually giving it back?")
    cutscene:jumpTo("aqua", 680.0, 240.0, 10, 1, "spin")
    cutscene:text("[image:aquaf, 0, 0, 2, 2][color:#24deff] Uuuuu! Kim let's tell the others what we saw!")
    cutscene:text("[voice:maytxt]* Aww they drew little pictures in it!")
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]Yeah...[wait:5] It's actually kind of swe-[next]")
    cutscene:shakeCharacter("seth", 2, 1, 0.5)
    cutscene:setAnimation("seth", "WHAT")
    Game.world.music:pause()
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]WAIT WHAT?!")
    cutscene:playSound("escaped")
    cutscene:setAnimation("seth", "run")
    cutscene:look("may", "right")
    cutscene:walkTo("seth", 680.0, 280.0, 0.5)
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]AQUA NOOO!!!", nil, nil,
        { skip = false, advance = false })
    cutscene:wait(2)
    cutscene:look("may", "down")
    cutscene:text("[voice:maytxt]* Erm,[wait:5] what the [wait:5] [glow:170, 115, 1, 0, 0, 10][color:red][sound:ominous] b o o k?")

    cutscene:spin("may", 2)
    
    Game:setFlag("post_mayseth", true)
    cutscene:playSound("screenshake")
    cutscene:shakeCamera(4, 2, 1)
    cutscene:text("[image:sethf, -9, 0, 2, 2][color:pink]OW![wait:5] Screw this conviently placed lever!")
    
    cutscene:wait(cutscene:attachCamera(1))
    cutscene:attachFollowers(1)
    cutscene:text("[voice:ralsei][face:ralsei/dismissive, -15, -10] * ...O-[wait:5]okay????")
    Game:setFlag("post_mayseth_save", true)

 end
}

